### ISSUE TITLE
Number of benchmark warmup rounds is sometimes not enough for PyPy

### ISSUE THREAD

**Issue by thedrow** [ionelmc/pytest-benchmark#10]
See https://travis-ci.org/thedrow/drf-benchmarks/jobs/66443524#L420 for example.
I need a way to specify the minimum of warmup rounds for a benchmark so that I'll be able to verify that the JIT has been triggered.

**Comment by ionelmc** [comment]
Have you tried `--benchmark-warmup-iterations` or the `warmup` option for the benchmark marker (`@pytest.mark.benchmark`)?

Default is 100000 - maybe you need larger value for that test.

**Comment by ionelmc** [comment]
Eg:
```
@pytest.mark.benchmark(warmup=10000000)
def test_nested_object_serialization(....
```

**Comment by thedrow** [comment]
The CLI help says that this is the maximum rounds that will run during the warmup phase but if that's the maximum of rounds then I understand that there's no minimum.
It can run even once.

**Comment by ionelmc** [comment]
Whoops. Yes you are correct. It will obey the max warmup iterations AND max
time, whichever comes first.

Would using a larger max time be an acceptable workaround for you?

On Friday, June 12, 2015, Omer Katz <notifications@github.com> wrote:

> The CLI help says that this is the maximum rounds that will run during the
> warmup phase but if that's the maximum of rounds then I understand that
> there's no minimum.
> It can run even once.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ionelmc/pytest-benchmark/issues/10#issuecomment-111476553>
> .
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by ionelmc** [comment]
Using large max time, in addition to larger warmup iterations I mean.

On Friday, June 12, 2015, Ionel Cristian Mărieș <contact@ionelmc.ro> wrote:

> Whoops. Yes you are correct. It will obey the max warmup iterations AND
> max time, whichever comes first.
>
> Would using a larger max time be an acceptable workaround for you?
>
> On Friday, June 12, 2015, Omer Katz <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> The CLI help says that this is the maximum rounds that will run during
>> the warmup phase but if that's the maximum of rounds then I understand that
>> there's no minimum.
>> It can run even once.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ionelmc/pytest-benchmark/issues/10#issuecomment-111476553>
>> .
>>
>
>
> --
>
> Thanks,
> -- Ionel Cristian Mărieș, http://blog.ionelmc.ro
>
>

-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by thedrow** [comment]
But that's not very obvious.
We either should document your proposed solution or add a new option that will specify the minimum warmup rounds.

**Comment by ionelmc** [comment]
The help strings can be improved sure, but I want to know what works for you.

When I implemented the warmup I had this idea of "time constraint". I wanted the `max-time` to be the ultimate constraint as a test that runs forever is not desirable. In other words `max-iterations` is slippery slope without `max-time` *applying some brakes*. Makes sense? :grin: 

Can you readjust your tests using larger `max-time` and report here what balance of settings you have found?

**Comment by ionelmc** [comment]
See 8e3a822

**Comment by thedrow** [comment]
I'll let you know once the build is finished.
https://travis-ci.org/thedrow/drf-benchmarks/builds/66689909

**Comment by thedrow** [comment]
The build now fails because it exceeds the 2 hours limit.
I have to look into this a bit more.

**Comment by thedrow** [comment]
I tried to raise the maximum benchmark time for some reason the maximum length is much worse:
```
 benchmark 'ModelSerializer deserialization': 18 tests, min 5 rounds (of min 25.00us), 1.00s max time, timer: pytest_benchmark.timers.monotonic 
Name (time in us)                                   Min         Max      Mean    StdDev   Rounds  Iterations
------------------------------------------------------------------------------------------------------------
test_object_deserialization                     20.9130  10387.6500   22.4716   30.9971  2835405           1
test_object_list_deserialization[2]             41.9020  10263.1960   45.1219   49.9471  1423117           1
test_object_list_deserialization[3]             62.0200  10483.0650   69.4924   67.8175   963314           1
test_object_list_deserialization[4]             82.1980  10512.3910   90.7690   85.4733   727247           1
test_object_list_deserialization[5]            102.5870  29289.3800  129.9045  137.2858   579907           1
test_object_list_deserialization[6]            122.3680  11559.6230  138.9940  123.9069   485245           1
test_object_list_deserialization[7]            143.4580  11140.9380  161.5382  138.9299   417909           1
test_object_list_deserialization[8]            163.4620  11613.9450  186.0623  153.2917   364563           1
test_object_list_deserialization[9]            183.0980  16556.1510  217.9215  186.0174   324592           1
test_nested_object_deserialization              29.9170  10040.4400   32.8142   42.5050  1990512           1
test_nested_object_list_deserialization[2]      59.7880  10312.7010   65.0294   71.1877   994201           1
test_nested_object_list_deserialization[3]      89.0820  10276.0360   95.9430   97.2147   663894           1
test_nested_object_list_deserialization[4]     119.9640  11013.2520  130.4340  125.7047   496324           1
test_nested_object_list_deserialization[5]     149.0940  12365.6990  165.5242  152.1852   398637           1
test_nested_object_list_deserialization[6]     179.9780  11162.9670  204.4562  179.6112   332125           1
test_nested_object_list_deserialization[7]     209.2490  12408.0490  234.9290  206.1324   285492           1
test_nested_object_list_deserialization[8]     239.3190  14880.9080  280.4062  237.0569   250531           1
test_nested_object_list_deserialization[9]     267.4010  16110.2060  307.1908  258.1168   221337           1
------------------------------------------------------------------------------------------------------------

 benchmark 'ModelSerializer serialization': 18 tests, min 5 rounds (of min 25.00us), 1.00s max time, timer: pytest_benchmark.timers.monotonic 
Name (time in us)                                 Min         Max      Mean    StdDev   Rounds  Iterations
----------------------------------------------------------------------------------------------------------
test_object_serialization                     24.2520  12174.4330   25.8629   30.0132  2449180           1
test_object_list_serialization[2]             48.9320   2715.9180   52.4098   27.5820    20275           1
test_object_list_serialization[3]             73.0730    453.4320   75.6170   13.2839    13550           1
test_object_list_serialization[4]             97.1510  11612.3880  104.8649  194.6716    10299           1
test_object_list_serialization[5]            120.7720    499.9200  124.5871   17.5029     8269           1
test_object_list_serialization[6]            145.0480    546.2010  150.0348   19.3959     6896           1
test_object_list_serialization[7]            168.9910  11838.8950  183.9964  263.7645     5912           1
test_object_list_serialization[8]            194.0450    596.5390  200.0954   22.4840     5180           1
test_object_list_serialization[9]            217.3020  12731.8630  235.4812  314.0129     4601           1
test_nested_object_serialization              51.8160  12870.6620   55.1100   50.5206  1154069           1
test_nested_object_list_serialization[2]      48.7810  12977.6120   51.6094   44.0616  1222893           1
test_nested_object_list_serialization[3]      71.9520  12653.8030   77.0859   58.1702   827552           1
test_nested_object_list_serialization[4]      96.9280  13115.4440  102.9396   77.6543   622330           1
test_nested_object_list_serialization[5]      83.2770  13272.0590  108.8441   83.8458   500936           1
test_nested_object_list_serialization[6]      99.8660  11505.2380  108.4697   86.0366   599869           1
test_nested_object_list_serialization[7]     116.4640  10210.3650  124.8556  100.4619   517193           1
test_nested_object_list_serialization[8]     133.5380  10088.0580  143.7240  109.8505   451071           1
test_nested_object_list_serialization[9]     150.0230   9707.1740  162.1958  119.9874   403511           1
----------------------------------------------------------------------------------------------------------
```

**Comment by ionelmc** [comment]
Looks like you have found a bug in the calibration code (there's a single iteration) :grimacing:

**Comment by ionelmc** [comment]
Ok, so it turns out the single iteration is fine (your test functions are way slower than the 300nanosecond time resolution).

There was a bug witch could cause the suite to run forever (fixed in master).

About the high `Max` values you have, I suspect it's just how PyPy works. It could be gc pauses? Hmmmm ...

**Comment by ionelmc** [comment]
I get this with GC off:
```
py.test tests/test_calibration.py --benchmark-verbose -vv --benchmark-disable-gc -k xfast
============================================ test session starts ============================================
platform linux2 -- Python 2.7.9[pypy-2.6.0-final] -- py-1.4.28 -- pytest-2.7.1 -- /home/ionel/osp/pytest-benchmark/.env/pypy-pytest27-xdist/bin/python
cachedir: /home/ionel/osp/pytest-benchmark/.cache
rootdir: /home/ionel/osp/pytest-benchmark, inifile: setup.cfg
plugins: benchmark, cache, runfailed, cov, xdist, instafail
collected 4 items

tests/test_calibration.py::test_calibrate_xfast
  Timer precision: 300.00ns
  Calibrating to target round 30.00us; will estimate when reaching 3.00us.
    warmed up for 10.00s (6524113 x 1 iterations).
  - measured 1 iterations: 400.00ns.
    warmed up for 10.00s (6324071 x 10 iterations).
  - measured 10 iterations: 400.00ns.
    warmed up for 1.79s (1000000 x 100 iterations).
  - measured 100 iterations: 500.00ns.
    warmed up for 315.51ms (100000 x 1000 iterations).
  - measured 1000 iterations: 1.60us.
    warmed up for 169.39ms (10000 x 10000 iterations).
  - measured 10000 iterations: 12.60us.
  * estimating 23809 iterations.
    warmed up for 145.55ms (4201 x 23809 iterations).
  - measured 23809 iterations: 29.70us.

  Running 336701 rounds ...
  Ran for 11.54s.
PASSED

 benchmark: 1 tests, min 5 rounds (of min 25.00us), 1.00s max time, timer: pytest_benchmark.timers.monotonic
Name (time in ns)           Min       Max    Mean  StdDev  Rounds  Iterations
-----------------------------------------------------------------------------
test_calibrate_xfast     1.1676  361.2457  1.4019  2.2902  336701       23809
-----------------------------------------------------------------------------

====================================== 3 tests deselected by '-kxfast' ======================================
================================== 1 passed, 3 deselected in 34.99 seconds ==================================
__________________________________________________ summary __________________________________________________
```

**Comment by thedrow** [comment]
Should I try with master?

**Comment by ionelmc** [comment]
I've tried your tests again, there's still high max, even with the JIT disabled. I suspect these spikes in duration are caused by pypy's GC. On pypy `gc.disable()` doesn't really do anything, see http://pypy.readthedocs.org/en/latest/cpython_differences.html 

>    some functions and attributes of the gc module behave in a slightly different way: for example, gc.enable and gc.disable are supported, but instead of enabling and disabling the GC, they just enable and disable the execution of finalizers.

**Comment by thedrow** [comment]
I don't think there's anything else to do about this unfortunately. I just ignore max on PyPy.
