### ISSUE TITLE
[Bug] Running with --benchmark-histogram on a specific file causes misnaming

### ISSUE THREAD

**Issue by matthewfeickert** [ionelmc/pytest-benchmark#102]
# Description

As outlined in the [command line options](http://pytest-benchmark.readthedocs.io/en/stable/usage.html#commandline-options) for `--benchmark-histogram`
>--benchmark-histogram=FILENAME-PREFIX
> Plot graphs of min/max/avg/stddev over time in FILENAME-PREFIX-test_name.svg. If FILENAME-PREFIX contains slashes (‘/’) then directories will be created. Default: ‘benchmark_\<date>_\<time>’, example: ‘benchmark_20150811_041632’.

to pass a name prefix other than the default one should pass that after the `--benchmark-histogram` flag. However, if one wants to run on a specific test file _and_ use the default naming scheme this causes the file path to be interpreted as the file prefix and all tests are run.

Would it be reasonable to require that for a non-default name to be used that the `=` would be required?

# Expected Behavior

```
pytest --benchmark-histogram tests/test_benchmark.py
```
This would run the the tests in `test_benchmark.py` and then save the histogram with the default name. So after running this you would expect to find
```
$ ls *.svg
benchmark_<date>_<time>.svg
```

This works as expected
```
$ pytest --benchmark-histogram=example tests/test_benchmark.py
$ ls example.svg 
example.svg
```

# Actual Behavior

```
pytest --benchmark-histogram tests/test_benchmark.py
```
This interprets `tests/test_benchmark.py` as the desired name of the file and runs all the tests instead of only the tests in `tests/test_benchmark.py` 
```
$ pytest --benchmark-histogram tests/test_benchmark.py
$ ls *.svg
$ ls tests/test_benchmark.py.svg 
tests/test_benchmark.py.svg
```
# Operating system name and version

OS: Ubuntu 16.04 LTS
```
$ uname -a
Linux ThinkPad-Edge-E540 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Version of `pytest-benchmark`: [v3.1.1](https://github.com/ionelmc/pytest-benchmark/releases/tag/v3.1.1)
```
$ python --version
Python 3.6.4 :: Anaconda, Inc.
$ py.test --version
This is pytest version 3.4.0, imported from /home/mcf/anaconda3/envs/pyhf/lib/python3.6/site-packages/pytest.py
setuptools registered plugins:
  pytest-cov-2.5.1 at /home/mcf/anaconda3/envs/pyhf/lib/python3.6/site-packages/pytest_cov/plugin.py
  pytest-benchmark-3.1.1 at /home/mcf/anaconda3/envs/pyhf/lib/python3.6/site-packages/pytest_benchmark/plugin.py
```

# Steps to Reproduce

With directory `tests` and a file `tests/test_benchmark.py` run
```
pytest --benchmark-histogram tests/test_benchmark.py
```

**Comment by ionelmc** [comment]
Ah ... this is the same issue with the `--cov` option from pytest-cov. Can't really be fixed. The workaround is to specify `--becnhmark-histogram` as the last option so it doesn't eat up the test collecting paths.

**Comment by matthewfeickert** [comment]
@ionelmc Thanks for the reply. Ah, okay, well this is good to know. 
> The workaround is to specify `--becnhmark-histogram` as the last option so it doesn't eat up the test collecting paths.

I think this is a fine solution by itself, so I think we can close this now. Thanks!
