### ISSUE TITLE
Comparing existing benchmarks without running the benchmark again

### ISSUE THREAD

**Issue by mariokostelac** [ionelmc/pytest-benchmark#132]
I am wondering whether there is a way to compare existing runs without running the benchmark again.

**Comment by ionelmc** [comment]
Yes, there is a separate CLI, see: https://pytest-benchmark.readthedocs.io/en/latest/usage.html#comparison-cli

Suggestions welcome for how to make this easier to find.

**Comment by mariokostelac** [comment]
That seems like an important feature to me. Would making an item in the main menu be too much?

**Comment by ionelmc** [comment]
Sure, suggest a title.

**Comment by mariokostelac** [comment]
Comparing results. And then we could explain that there are two ways to compare results. One with CLI tool or the other one, straight after running. If you want I can try to make a PR during the weekend.
