### ISSUE TITLE
benchmarking side-effectful code

### ISSUE THREAD

**Issue by vmagdin** [ionelmc/pytest-benchmark#14]
I'm working on benchmarking some functions that modify their input. The input is a list of dictionaries, and the code sorts the list and also adds things to the dictionaries. As a result of this, the benchmarks are not totally true, because the first iteration modifies the input and the consequent iterations have to do much less work, because the input is already sorted. 

I can "fix" this problem by doing something (expensive) like deepcopy before the function I'm benchmarking is run, however, this will add to the running time statistics. Any thoughts?

**Comment by ionelmc** [comment]
@vmagdin is it correct to assume you're looking for some sort of setup function?

Eg (not implemented, just sketching a proposal):

```python
def test_foo(benchmark):
    def setup():
        return ({'foo': 'bar'},), {} # returning (positional args, keyword args)
    def cleanup():
         pass
    benchmark(some_func, setup, cleanup)

```

Actually I don't like that API at all, any other suggestions?

**Comment by ionelmc** [comment]
Alternative API, that doesn't break backwards compatibility:
```
def test_foo(benchmark):
    def setup():
        return ({'foo': 'bar'},), {} # returning (positional args, keyword args)
    def cleanup():
         pass
    benchmark.run(some_func, setup, cleanup)
```

Note the `.run`.

There's a slight problem here: Calibration needs to be disabled (it won't work anyway, due to individual measurements). Also, see #9.

@vmagdin The functions you're benchmarking don't take *less* than 100 microseconds right? If they are faster than 100 µs, then I'm afraid the results may not be that useful :disappointed:

**Comment by ionelmc** [comment]
@thedrow regarding your question on IRC, this would solve your issue. But you don't need calibration at all? How fast is your test function?

**Comment by thedrow** [comment]
Here are the results so you tell me: https://travis-ci.org/thedrow/drf-benchmarks/jobs/76134628#L491
I'm not sure why providing parameters will disable calibration though.
Couldn't you just create the fixture values ahead of time and just pop them when you call the benchmark?

**Comment by ionelmc** [comment]
Could you post an example of how you would use the the parameters? Maybe your issue is different after all :)

**Comment by thedrow** [comment]
```python
@pytest.fixture
def serializer():
  return MySerializer()
@pytest.mark.benchmark
def test_foo(benchmark):
  @benchmark
  def result(serializer):
    serializer.to_representation()
```

**Comment by ionelmc** [comment]
I've fixed the PyPy issue in https://github.com/ionelmc/pytest-benchmark/commit/6b0bd7ecc6ad2a3faba2ad108f42b65b5863321a - you should do this instead:
```python
@pytest.fixture
def serializer():
  return MySerializer()

@pytest.mark.benchmark
def test_foo(benchmark, serializer):
  benchmark(serializer.to_representation)
```

**Comment by thedrow** [comment]
But this won't recreate the serializer with every benchmark run. It's still way more comfortable to write it this way though :+1:

**Comment by ionelmc** [comment]
@vmagdin @thedrow I've implemented a "manual" mode with setup function and fine control over rounds/iterations (no automatic calibration) in master, `pip install https://github.com/ionelmc/pytest-benchmark/archive/master.zip`. This should solve all these special usecases. Let me know if you'd like any changes on the API.

**Comment by ionelmc** [comment]
Here be some docs: http://pytest-benchmark.readthedocs.org/en/latest/pedantic.html
