### ISSUE TITLE
 How to pass the calculation results in BenchmarkFixture to hookspec

### ISSUE THREAD

**Issue by Tom-Deng** [ionelmc/pytest-benchmark#172]
according to unitest:
https://github.com/ionelmc/pytest-benchmark/blob/dafa578d034525475fe7a7e14b085315e15a14e2/tests/test_benchmark.py
![image](https://user-images.githubusercontent.com/17919002/82440144-73811000-9ace-11ea-8c8a-f379b1306961.png)

In our scene，we want to update benchmark json, but the updated contents were   calculation results in BenchmarkFixture.

for example:
test_simple.py like this:
![image](https://user-images.githubusercontent.com/17919002/82440531-1174da80-9acf-11ea-9756-7a5be299f4fc.png)
conftest.py  like this:
![image](https://user-images.githubusercontent.com/17919002/82440641-41bc7900-9acf-11ea-9ae5-ea09177ea3b8.png)

How to pass resuilt's result to pytest_benchmark_update_json?

Type of benchmark is pytest_benchmark.fixture.BenchmarkFixture.

**Comment by ionelmc** [comment]
See: https://pytest-benchmark.readthedocs.io/en/latest/usage.html#extra-info

**Comment by ionelmc** [comment]
Eg, in your situation you'd have:

```python

def test_simple(benchmark):
    @benchmark
    def result():
        ...
    benchmark.extra_info['result'] = result
```
