### ISSUE TITLE
Add Ability To Overwrite BenchmarkFixture Class

### ISSUE THREAD

**Issue by rmorshea** [ionelmc/pytest-benchmark#174]
There's some custom things that I'd like to customize about the `BenchmarkFixture` class however there's not a simple way to do this. If there were a `benchmark_type` fixture which was used by `benchmark` to construct the `BenchmarkFixture` instance I'd be able to control this.

The changes might look something like this:

```python
@pytest.fixture(scope="function")
def benchmark_type():
    return BenchmarkFixture

@pytest.fixture(scope="function")
def benchmark(request, benchmark_type):
    ...
    fixture = benchmark_type(...)
    ...
    return fixture
```

This way I could define my own `benchmark_type` fixture.

**Comment by ionelmc** [comment]
Yes, there could be. You don't need this anymore?

**Comment by rmorshea** [comment]
I don't need this anymore. It's been long enough that I don't remember what things I wanted/needed it for too.
