### ISSUE TITLE
Release a new version on pypi?

### ISSUE THREAD

**Issue by aldanor** [ionelmc/pytest-benchmark#18]
The current version that's out there has a Python 3 syntax error (`except` clause) so it's broken and not installable -- might make sense to release a new one since that error has been fixed?

**Comment by ionelmc** [comment]
Do you have a traceback?

The current master is slated to be a 3.0.0 and it's close to release (I'm tweaking few things now).

**Comment by aldanor** [comment]
It's basically this one: https://github.com/ionelmc/pytest-benchmark/pull/17

**Comment by ionelmc** [comment]
Oh, that file is not really useful (it provides some functions that were added in 3.4). You can safely use pytest-benchmark on 3.4+ - you don't need the pep418 module at all.

**Comment by ionelmc** [comment]
I can make a 2.5.1 release right now if you want to use python 3.3 - is that the case?

**Comment by aldanor** [comment]
It's not a runtime problem but rather install-time -- setuptools tries to byte-compile modules when installing and then that fails (it's on python3.4):

```
running build
running build_py
creating dist/lib
creating dist/lib/pytest_benchmark
copying src/pytest_benchmark/__init__.py -> dist/lib/pytest_benchmark
copying src/pytest_benchmark/compat.py -> dist/lib/pytest_benchmark
copying src/pytest_benchmark/pep418.py -> dist/lib/pytest_benchmark
copying src/pytest_benchmark/plugin.py -> dist/lib/pytest_benchmark
copying src/pytest_benchmark/stats.py -> dist/lib/pytest_benchmark
copying src/pytest_benchmark/timers.py -> dist/lib/pytest_benchmark
running egg_info
writing entry points to src/pytest_benchmark.egg-info/entry_points.txt
writing dependency_links to src/pytest_benchmark.egg-info/dependency_links.txt
writing top-level names to src/pytest_benchmark.egg-info/top_level.txt
writing src/pytest_benchmark.egg-info/PKG-INFO
writing requirements to src/pytest_benchmark.egg-info/requires.txt
reading manifest file 'src/pytest_benchmark.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'examples'
warning: no directories found matching 'ci'
warning: no files found matching '.bumpversion.cfg'
warning: no files found matching '.isort.cfg'
warning: no files found matching '.pylintrc'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'src/pytest_benchmark.egg-info/SOURCES.txt'
running install
running install_lib
creating env/lib/python3.4/site-packages/pytest_benchmark
copying dist/lib/pytest_benchmark/__init__.py -> env/lib/python3.4/site-packages/pytest_benchmark
copying dist/lib/pytest_benchmark/compat.py -> env/lib/python3.4/site-packages/pytest_benchmark
copying dist/lib/pytest_benchmark/pep418.py -> env/lib/python3.4/site-packages/pytest_benchmark
copying dist/lib/pytest_benchmark/plugin.py -> env/lib/python3.4/site-packages/pytest_benchmark
copying dist/lib/pytest_benchmark/stats.py -> env/lib/python3.4/site-packages/pytest_benchmark
copying dist/lib/pytest_benchmark/timers.py -> env/lib/python3.4/site-packages/pytest_benchmark
byte-compiling env/lib/python3.4/site-packages/pytest_benchmark/__init__.py to __init__.cpython-34.pyc
byte-compiling env/lib/python3.4/site-packages/pytest_benchmark/compat.py to compat.cpython-34.pyc
byte-compiling env/lib/python3.4/site-packages/pytest_benchmark/pep418.py to pep418.cpython-34.pyc
byte-compiling env/lib/python3.4/site-packages/pytest_benchmark/plugin.py to plugin.cpython-34.pyc
byte-compiling env/lib/python3.4/site-packages/pytest_benchmark/stats.py to stats.cpython-34.pyc
byte-compiling env/lib/python3.4/site-packages/pytest_benchmark/timers.py to timers.cpython-34.pyc
running install_egg_info
Copying src/pytest_benchmark.egg-info to env/lib/python3.4/site-packages/pytest_benchmark-2.5.0-py3.4.egg-info
running install_scripts
  File "env/lib/python3.4/site-packages/pytest_benchmark/pep418.py", line 47
    except ImportError, err:
                      ^
SyntaxError: invalid syntax
```

**Comment by ionelmc** [comment]
Those are just warnings. Are you sure it didn't install?

**Comment by aldanor** [comment]
Oh, yea, indeed. It's a part of a much large build system that I'm running that purposefully fails on any syntax errors found when installing (basically port of tox to conda's environments), so that's why....

I managed to get it working git master branch, so if you're planning on releasing 3.0 soon anyway it's probably fine

**Comment by ionelmc** [comment]
There are only two things that I want to do before release:

* [ ] remove dead code and/or increase test coverage
* [ ] polish a bit the `benchmark.manual` api - don't use that yet, renaming might be possible :-)

**Comment by ionelmc** [comment]
Released `3.0.0a1`

**Comment by aldanor** [comment]
That's great, thanks!

By the way, I've had a bunch of suggestions after using pytest-benchmark for a while, should I just dump them all into one issue?

**Comment by ionelmc** [comment]
However you want. If they are not really related to each other the maybe
individual issues is better

On Sunday, September 13, 2015, Ivan Smirnov <notifications@github.com>
wrote:

> That's great, thanks!
>
> By the way, I've had a bunch of suggestions after using pytest-benchmark
> for a while, should I just dump them all into one issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ionelmc/pytest-benchmark/issues/18#issuecomment-139873178>
> .
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by anarcat** [comment]
it would be nice to see a *stable* release put out because right now `pip install pytest-benchmark` installs 2.5 here, and this warning shows up. it *does* get installed fine, but it's a little confusing at first...

**Comment by ionelmc** [comment]
I know it's annoying but I just want to get it right. I have this unshakable feeling that I got something wrong in 3.0 - please give feedback :grin:

**Comment by anarcat** [comment]
sorry for the dumb question, but how do i install 3.0?

**Comment by ionelmc** [comment]
`pip install pytest-benchmark==3.0.0a3` or `pip install --pre pytest-benchmark`

**Comment by anarcat** [comment]
3.0.0a3 looks fine here, thanks for the tip
