### ISSUE TITLE
Remove 'See calibration_ and FAQ_.' from project summary

### ISSUE THREAD

**Issue by mcsitter** [ionelmc/pytest-benchmark#181]
It would be awesome if 'See calibration_ and FAQ_.' could be removed from the `description` in `setup.py`.
I could not find a place in which the links would work, but they get shown everywhere, where there is the description of the project, such as on the [project page on pypi](https://pypi.org/project/pytest-benchmark/) and the current [plugin list](https://plugincompat.herokuapp.com/) of pytest, which is getting reworked as of pytest-dev/pytest#5105 .

before:
```python
    description='A ``pytest`` fixture for benchmarking code. It will group the tests into rounds that are calibrated to the chosen timer. '
                'See calibration_ and FAQ_.',
```

after:
```python
    description='A ``pytest`` fixture for benchmarking code. It will group the tests into rounds that are calibrated to the chosen timer. ',
```

It is also in the `README.rst` and `.cookiecutterrc`. I can understand if updating the cookiecutter details and the docs is undesired, but i see no problem in updating the package metadata.

I would be happy to open a PR if you agree with this proposal!

**Comment by ionelmc** [comment]
Those are named references, I guess there's a problem with those. We could convert those to regular links to the latest docs - would that work in the plugin list?

**Comment by mcsitter** [comment]
I think it would work for the plugin list, but the project page would be become really ugly. I don't think they render the description for the header [here](https://github.com/pypa/warehouse/blob/cfef3488e94ff4b86cfd188b86fb7678d083354f/warehouse/templates/packaging/detail.html#L153-L154). It is probably just the text. [summary in Realease database model](https://github.com/pypa/warehouse/blob/bd2b3a22f4f84072eb03abb771a88ddab1489e7a/warehouse/packaging/models.py#L364)

**Comment by ionelmc** [comment]
Alright fine, lets just remove them.
