### ISSUE TITLE
machine_info['cpu'] become always unknown

### ISSUE THREAD

**Issue by miurahr** [ionelmc/pytest-benchmark#193]
Because dependnecy py-cpuinfo v6.0.0 changed API
https://github.com/workhorsy/py-cpuinfo/pull/123/files

`machine_info['cpu']['brand']` `machine_info['cpu']['vendor_id']` and `machine_info['cpu']['hardware']` become always `unknown` value.

Here is the citation from py-cpuinfo/README.md

Raw Fields
-----

These fields are pulled directly from the CPU and are unverified. They may
contain expected results. Other times they may contain wildly unexpected
results or garbage. So it would be a bad idea to rely on them.

| key                           | Example value             | Return Format         |
| :---------------------------- | :------------------------ | :-------------------- |
| "vendor_id_raw"               | "GenuineIntel"            | string                |
| "hardware_raw"                | "BCM2708"                 | string                |
| "brand_raw"                   | "Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz" | string                |
| "arch_string_raw"             | "x86_64"                  | string                |

**Comment by ionelmc** [comment]
Those are added there for historical reference, the comparison code doesn't rely on this data - it's just there so you have it in case you need it.

**Comment by miurahr** [comment]
There is not a description to explain default `machine_info['cpu']` is useless, or `historical reference`, and it is mandatory to custom it by `generate_machine_info`  before use it for comparison.
https://pytest-benchmark.readthedocs.io/en/latest/hooks.html#pytest_benchmark.hookspec.pytest_benchmark_compare_machine_info

An example make users feel the fields usable in default.

**Comment by miurahr** [comment]
Could you put `machine_info['cpu']['arch']` and `machine_info['cpu']['count']`instead of these three `unknown` values?
It is useful in default.

**Comment by ionelmc** [comment]
Maybe I should just dump all the fields - what do you think?

**Comment by miurahr** [comment]
It is good idea except for some fields, such as `python_version`, `cpuinfo_version_string` and `cpuinfo_version`.

**Comment by ionelmc** [comment]
Is it worth filtering those fields at all? Seeing how the filters broke things previously I wouldn't bother anymore...

**Comment by miurahr** [comment]
Looks good.

**Comment by ionelmc** [comment]
Fixed in master.
