### ISSUE TITLE
Comparison table not right?

### ISSUE THREAD

**Issue by Spectre5** [ionelmc/pytest-benchmark#194]
When I run with `--benchmark-compare`, it compares all tests together instead of separately comparing each of the test functions.  How can I get it to compare each test separately?

    $ pytest -x --benchmark-storage=.cache/benchmarks --benchmark-autosave --benchmark-compare
    Comparing against benchmarks from: Linux-CPython-3.8-64bit/0017_ae7ddd9a45ce97d104c6beebeee5aaa2b2d7bd55_20210221_231948_uncommited-changes.json
    ============================================================================================== test session starts ===============================================================================================
    platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
    benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
    rootdir: /home/<snip>
    plugins: hypothesis-6.3.0, benchmark-3.2.3
    collected 5 items                                                                                                                                                                                                

    tests/test_example.py ..                                                                                                                                                                 [100%]
    Saved benchmark data in: /home/<snip>/.cache/benchmarks/Linux-CPython-3.8-64bit/0018_ae7ddd9a45ce97d104c6beebeee5aaa2b2d7bd55_20210221_232123_uncommited-changes.json

    ---------------------------------------------------------------------------------------------- benchmark: 6 tests ---------------------------------------------------------------------------------------------
    Name (time in ms)                        Min                   Max                  Mean             StdDev                Median                IQR            Outliers      OPS            Rounds  Iterations
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    test_1 (NOW)                         25.9614 (1.0)         26.7989 (1.0)         26.2850 (1.0)       0.2422 (1.86)        26.2250 (1.0)       0.3782 (3.87)         12;0  38.0445 (1.0)          38           1
    test_1 (0017_ae7ddd9)                26.4183 (1.02)        27.0430 (1.01)        26.5549 (1.01)      0.1301 (1.0)         26.5203 (1.01)      0.0978 (1.0)           5;3  37.6579 (0.99)         37           1
    test_2 (NOW)                        502.0464 (19.34)      564.8274 (21.08)      534.6141 (20.34)    29.1967 (224.40)     541.7351 (20.66)    55.0144 (562.75)        2;0   1.8705 (0.05)          5           1
    test_2 (0017_ae7ddd9)               505.7677 (19.48)      513.2472 (19.15)      508.5874 (19.35)     2.9334 (22.55)      508.1235 (19.38)     3.8804 (39.69)         1;0   1.9662 (0.05)          5           1
    test_3 (NOW)                      2,930.4952 (112.88)   3,144.5371 (117.34)   2,988.5274 (113.70)   88.5852 (680.85)   2,952.7849 (112.59)   76.4680 (782.20)        1;1   0.3346 (0.01)          5           1
    test_3 (0017_ae7ddd9)             2,959.1996 (113.98)   2,978.7907 (111.15)   2,966.4838 (112.86)    7.8562 (60.38)    2,964.2083 (113.03)   11.0282 (112.81)        1;0   0.3371 (0.01)          5           1
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    Legend:
      Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
      OPS: Operations Per Second, computed as 1 / Mean
    =============================================================================================== 5 passed in 44.46s ===============================================================================================

I expected to see something more like below, where of course the ratios for the comparison (in the parentheticals) would be adjusted to compare only the two tests together.

    ---------------------------------------------------------------------------------------------- benchmark 'test_1': 2 tests ------------------------------------------------------------------------------------
    Name (time in ms)                        Min                   Max                  Mean             StdDev                Median                IQR            Outliers      OPS            Rounds  Iterations
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    test_1 (NOW)                         25.9614 (1.0)         26.7989 (1.0)         26.2850 (1.0)       0.2422 (1.86)        26.2250 (1.0)       0.3782 (3.87)         12;0  38.0445 (1.0)          38           1
    test_1 (0017_ae7ddd9)                26.4183 (1.02)        27.0430 (1.01)        26.5549 (1.01)      0.1301 (1.0)         26.5203 (1.01)      0.0978 (1.0)           5;3  37.6579 (0.99)         37           1
    
    ---------------------------------------------------------------------------------------------- benchmark 'test_2': 2 tests ------------------------------------------------------------------------------------
    Name (time in ms)                        Min                   Max                  Mean             StdDev                Median                IQR            Outliers      OPS            Rounds  Iterations
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    test_2 (NOW)                        502.0464 (19.34)      564.8274 (21.08)      534.6141 (20.34)    29.1967 (224.40)     541.7351 (20.66)    55.0144 (562.75)        2;0   1.8705 (0.05)          5           1
    test_2 (0017_ae7ddd9)               505.7677 (19.48)      513.2472 (19.15)      508.5874 (19.35)     2.9334 (22.55)      508.1235 (19.38)     3.8804 (39.69)         1;0   1.9662 (0.05)          5           1

    ---------------------------------------------------------------------------------------------- benchmark 'test_3': 2 tests ------------------------------------------------------------------------------------
    Name (time in ms)                        Min                   Max                  Mean             StdDev                Median                IQR            Outliers      OPS            Rounds  Iterations
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    test_3 (NOW)                      2,930.4952 (112.88)   3,144.5371 (117.34)   2,988.5274 (113.70)   88.5852 (680.85)   2,952.7849 (112.59)   76.4680 (782.20)        1;1   0.3346 (0.01)          5           1
    test_3 (0017_ae7ddd9)             2,959.1996 (113.98)   2,978.7907 (111.15)   2,966.4838 (112.86)    7.8562 (60.38)    2,964.2083 (113.03)   11.0282 (112.81)        1;0   0.3371 (0.01)          5           1
    ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by ionelmc** [comment]
You probably want to use `--benchmark-group-by=name`.

**Comment by Spectre5** [comment]
Ah, I thought I checked all of the options but I clearly missed that one, thanks!  Perhaps add just before the screenshots in the `README` what the exact command executed was?  Or include that part of the screen shot?
