### ISSUE TITLE
Allow to configure columns reported

### ISSUE THREAD

**Issue by aldanor** [ionelmc/pytest-benchmark#21]
Referring again to the output of pytest-benchmark's test suite itself, I'd point out that it is 188 characters wide which is a lot more than 80 or 100.

In a lot of cases, you would just want some mix of mean/median/min/max; especially so in the manual mode when you know exactly what you are doing.

Like, I could look at the outliers, stddev and IQR while designing the benchmark, but when it's being reported at the end of the test suite run, I'll probably just look at min/mean.

With this in mind, it would be then nice if the report could be configured to include/exclude custom stat columns, like `stats=['min', 'mean'], sort='min'` (or command line parameters). Maybe the default setting should be not to output absolutely every stat that it computes, too.

**Comment by ionelmc** [comment]
Maybe a `--benchmark-report-columns=min,mean,blabla` option?

**Comment by aldanor** [comment]
Yep that sounds about right.

**Comment by makmanalp** [comment]
Looks like this might be done now since we have `--columns LABELS`?

**Comment by ionelmc** [comment]
Ah yes, thanks, I forgot to close this.
