### ISSUE TITLE
No test are choosen when directory is specified in command line

### ISSUE THREAD

**Issue by nirupbbnk** [ionelmc/pytest-benchmark#229]
**Env Details**
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
benchmark: 4.0.0 
When I keep all test files ending with .py and run test , no tests are selected 
`pytest service/microBenchmark/`
All the files are located in microBenchmark folder
But same works when individual file name is given 

**Output**
collected 0 items 
no tests ran

**Comment by ionelmc** [comment]
You're probably using a non-standard naming scheme and didn't configure python_files, see https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-python_files

**Comment by nirupbbnk** [comment]
@ionelmc Thanks a lot , it works after prefixing test_*
