### ISSUE TITLE
Error in pytest possibly relating to pytest-benchmark in version `5.0.0`

### ISSUE THREAD

**Issue by dpanici** [ionelmc/pytest-benchmark#271]
Hello,

Unsure if this is the main source of. the error or if it is an upstream bug with a package that depends on `pytest-benchmark`, but we use `pytest-benchmark` in our CI, in addition to other plugins to run jupyter notebooks as part of the CI.

Upon the update from `4.0.0` to `5.0.0` we've found our [CI failing](https://github.com/PlasmaControl/DESC/issues/1333), with the exact cause unclear, but it seems to relate to `pytest-benchmark` from the [error logs](https://github.com/PlasmaControl/DESC/actions/runs/11567604447/job/32198430312?pr=1119). 
The CI runner is on Linux, the details of the specifics and the environment are in the aforementioned linked error logs.

With `4.0.0` our tests pass. Again, unsure if this is a specific issue with `pytest-benchmark` or related to another package we use which depends on `pytest-benchmark` that broke when `5.0.0` was released, but if you have any insight into the error we are getting that would be greatly appreciated!

If it helps, our CI yml that is failing is https://github.com/PlasmaControl/DESC/blob/master/.github/workflows/notebook_tests.yml and line 79 of said file has the specific pytest command that results in the error.

**Comment by ionelmc** [comment]
Yeah I added a type check for the "benchmark" fixture is not defined to something else. The goal was to give a clear error message for situations like https://github.com/ionelmc/pytest-benchmark/issues/265.

In your project apparently that is not a problem (I guess you do define a "benchmark" fixture but it's scoping prevents the bad interaction in #265). I'll convert that to a warning....

**Comment by ionelmc** [comment]
So it's still an error but I fixed the check. Released a 5.0.1.
