### ISSUE TITLE
Make test suite fail if benchmark is unsatisfactory

### ISSUE THREAD

**Issue by alexprengere** [ionelmc/pytest-benchmark#40]
Hello,
I read the documentation and hope I did not miss something completely obvious.

My use case: I would like to use `pytest-benchmark` for continuous integration. A part of my test suite is actually performance tests, i.e. making sure that my `toto` function does not take longer than, let's say, 20ms.

I would like the test suite to *fail* is some modifications in the code make `toto()` exceeds the 20ms. I am aware of the `--benchmark-compare-fail=EXPR`, but I think what I am looking for is more specific.

I have no idea what would be the best way to describe this, perhaps:
```python
@pytest.mark.benchmark(fail_at=0.02)
def test_toto(benchmark):
    benchmark(toto)
```
Or maybe:
```python
def test_toto(benchmark):
    results = benchmark(toto, fail_at=0.02)
```
Or provide a way for the user to access the results of the benchmark? Before using `pytest-benchmark`, I would do something like this:
```python
def test_toto(benchmark):
    results = benchmark(toto)
    if results.average_time > 0.02:
        pytest.fail('Exceeding 20ms!')
```
Would this make sense in `pytest-benchmark`?

**Comment by ionelmc** [comment]
This would be possible:

```python
def test_toto(benchmark):
    result = benchmark(toto)
    # `result` is what toto() returns!
    if benchmark.stats.average_time > 0.02:
        pytest.fail('Exceeding 20ms!')
```

**Comment by ionelmc** [comment]
I mean, possible to implement :-)

**Comment by alexprengere** [comment]
Yes! I saw in the doc `result = benchmark(toto)` would get me `toto()`, but I wondered if there was a way to access other things regarding the benchmark in a similar way.

Your proposition looks good to me :wink:, it really gives  lot of flexibility to the end user. I put `average_time` in my example, but to keep things consistent with the command-line output, it should probably be `min/max/mean/stddev/median/iqr`.

**Comment by ionelmc** [comment]
FYI, it's fixed in master. Give it a try.

**Comment by alexprengere** [comment]
10 years later, I finally tested this 😉 
It turns out on this simple example:

```python
import time
import pytest

def toto():
    time.sleep(0.1)
    return 1

def test_toto(benchmark):
    _ = benchmark(toto)
    if benchmark.stats.mean > 0.02:
        pytest.fail('Exceeding 20ms!')
```
I actually have the following error:

```
AttributeError: 'Metadata' object has no attribute 'average_time'
```

Changing the code to this works as expected:

```python
    if benchmark.stats.stats.mean > 0.02:
    #            ^^^^^^^^^^^twice  
```
It is PR #59 that "broke" this. I do not min the "stats.stats", but I thought I would mention this, in case someone looks at this issue. Perhaps a convenience method could be added to `benchmark` here.
