### ISSUE TITLE
Colors appear to be broken

### ISSUE THREAD

**Issue by foxx** [ionelmc/pytest-benchmark#41]
As you can see, the colors appear to be broken on the `(*)` line, they are solid black, where as everything else is shaded "correctly". Any ideas?

![image](https://cloud.githubusercontent.com/assets/651797/12120837/6df48f4e-b3ca-11e5-8f8c-4e017fd35cfa.png)

**Comment by foxx** [comment]
Seems to be caused by this [line][1].

This was recently changed in a [commit][2] 2 days ago by @ionelmc, however it would appear `black=True` was on the original code as well.

Given that most terminals use dark backgrounds, and also that the rest of the CLI seems geared towards dark interfaces (`color=True` on lines), should the color not be something different?

[1]: https://github.com/ionelmc/pytest-benchmark/blob/efda8a505d72e2849eceb5bc37dd05324669ec71/src/pytest_benchmark/table.py#L123
[2]: https://github.com/ionelmc/pytest-benchmark/commit/55ff2431a3e3447b8e6be13edd48fdb7be02c376

**Comment by ionelmc** [comment]
I guess I could remove all the coloring for that line. 

In my terminal it looks like this:

![image 2](https://cloud.githubusercontent.com/assets/129501/12121574/a3031f8e-b3de-11e5-85ab-f285643bd203.png)

**Comment by ionelmc** [comment]
Out of curiosity, could you run this
```
#!/bin/bash
#
# Description:
#
#    Prints a color table of 8bg * 8fg * 2 states (regular/bold)
#
# Copyright:
#
#    (C) 2009 Wolfgang Frisch <xororand@unfoog.de>
#
# License:
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo
echo Table for 16-color terminal escape sequences.
echo Replace ESC with \\033 in bash.
echo
echo "Background | Foreground colors"
echo "---------------------------------------------------------------------"
for((bg=40;bg<=47;bg++)); do
        for((bold=0;bold<=1;bold++)) do
                echo -en "\033[0m"" ESC[${bg}m   | "
                for((fg=30;fg<=37;fg++)); do
                        if [ $bold == "0" ]; then
                                echo -en "\033[${bg}m\033[${fg}m [${fg}m  "
                        else
                                echo -en "\033[${bg}m\033[1;${fg}m [1;${fg}m"
                        fi
                done
                echo -e "\033[0m"
        done
        echo "--------------------------------------------------------------------- "
done

echo
echo
```
and make a screenshot?

**Comment by foxx** [comment]
Sure here you go.

Inside guest:

![image](https://cloud.githubusercontent.com/assets/651797/12121984/4f586fc8-b3d0-11e5-8926-6320e2931071.png)

Inside host;

![image](https://cloud.githubusercontent.com/assets/651797/12121997/6861c0be-b3d0-11e5-8473-e66a658f4a59.png)


Both guest and host appear to be the same.

**Comment by foxx** [comment]
Hmm, on your terminal it seems to be colored grey, similar to what we see in README. Given that it's `black=True`, is it possible you have some sort of color remapping in your terminal or shell which is changing the color from black to grey?

**Comment by ionelmc** [comment]
Most terminals allow you to have "themes". I think it's either blue or no color at all. Which one you like?

**Comment by foxx** [comment]
I'm guessing "no color" would actually result in a similar screenshot as what you posted earlier? (as most people have a grey color, rather than pure white). If so, I'd vote no color, thoughts?
