### ISSUE TITLE
Use sample code on package page, but got error

### ISSUE THREAD

**Issue by Asoul** [ionelmc/pytest-benchmark#43]
I use the sample code on [package page](https://pypi.python.org/pypi/pytest-benchmark). Below is my error:

```
[gw1] darwin -- Python 3.4.3 /Users/asoul/.virtualenvs/lms/bin/python3
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py:58: in testPartExecutor
    yield
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py:577: in run
    testMethod()
E   TypeError: test_my_stuff() missing 1 required positional argument: 'benchmark'
```

What should I do? Thanks :)

**Comment by ionelmc** [comment]
It's not clear what you're trying to do. Please create an [SSCCE](http://sscce.org/).

**Comment by ionelmc** [comment]
Assuming you want to write tests with TestCase, it's a bit more involved: https://github.com/ionelmc/pytest-benchmark/blob/master/tests/test_with_testcase.py

Also, heed the warning and don't use them TestCases, you don't need them with pytest.

**Comment by Asoul** [comment]
Thanks a lot! It works!

**Comment by Asoul** [comment]
But I found that benchmark does not display graph on multi-thread testing

For example, running the [code](https://github.com/ionelmc/pytest-benchmark/blob/master/tests/test_with_testcase.py) with

```
py.test -s --tb=short -k test_foo  test_with_testcase.py
```

works, but

```
py.test -s --tb=short -n 8 -k test_foo  test_with_testcase.py
```

will not show the graph

**Comment by Asoul** [comment]
My pytest plugin:

```
plugins: benchmark-3.0.0, xdist-1.14
```

**Comment by Asoul** [comment]
But thank you, I can run the benchmark now :)

**Comment by ionelmc** [comment]
Benchmarks are intentionally disabled on xdist (the `-n 8`) because of various issues. If you add `-ra` you should see the warning.

**Comment by stardust85** [comment]
If you use Django with multi-db setup, TestCase is the only way how to use it. So should be probably mentioned in the docs
