### ISSUE TITLE
Save raw data

### ISSUE THREAD

**Issue by Juanlu001** [ionelmc/pytest-benchmark#46]
Currently only the relevant statistics are saved to the `.json` file, but it would be nice to add some `--benchmark-full` command line option to actually save the elapsed time of each run too. I would like to take this results and plot them using tools other than pygal, so exporting them in some way would be helpful.

**Comment by ionelmc** [comment]
You mean you want all the datapoints?

Right now you can work around this by implementing a hook like this (in your `conftest.py`):
```
def pytest_benchmark_generate_json(config, benchmarks, include_data, machine_info, commit_info):
  from pytest_benchmark_plugin import pytest_benchmark_generate_json
  return pytest_benchmark_generate_json(config=config, benchmarks=benchmarks, include_data=True, machine_info=machine_info, commit_info=commit_info)
```

**Comment by ionelmc** [comment]
I will add a command line option in the next release.

**Comment by Juanlu001** [comment]
Exactly! Thanks for the suggestion, I will go that way for now. I love this project by the way :)

**Comment by Juanlu001** [comment]
Browsing the docs, I wonder if the `--benchmark-save-data` already does this? https://pytest-benchmark.readthedocs.org/en/latest/usage.html#commandline-options

**Comment by ionelmc** [comment]
Oh. Yes. It does. I have forgot about it - too many options :-)
