### ISSUE TITLE
Which test to run when packaging for linux distribution

### ISSUE THREAD

**Issue by DamienCassou** [ionelmc/pytest-benchmark#47]
Hi,

I'm packaging pytest-benchmark for nixos.org. Which tests should I run to make sure the packaging is ok? I saw you recommend nox but I would like a test for the current python environment, not for all of them. Moreover, I'm not interested in benchmark tests of pytest-benchmark. Thanks

**Comment by ionelmc** [comment]
You need to install the test deps you need (https://github.com/ionelmc/pytest-benchmark/blob/master/tox.ini#L37-L51) and then just run `py.test /path/to/tests`.

Tests aren't part of the installed package, so you'll need to be able to access them somehow (I don't know much about nix).

Also, pytest-benchmark doesn't really benchmark itself, it's just a bunch of (slow) integration tests. It can be made faster with some effort but is it too slow for you?

**Comment by DamienCassou** [comment]
Thanks. Indeed, they are a bit slow, but that's ok.
