### ISSUE TITLE
Error in pygal.graph.box import is_list_like

### ISSUE THREAD

**Issue by kirotawa** [ionelmc/pytest-benchmark#50]
version: pytest-benchmark-3.0.0 
How to reproduce:
py.test <file> --benchmark-histogram 

output:

File "/usr/local/lib/python2.7/dist-packages/pytest_benchmark/histogram.py", line 8, in <module>
    raise ImportError(exc.args, "Please install pygal and pygaljs or pytest-benchmark[histogram]")
ImportError: (('cannot import name is_list_like',), 'Please install pygal and pygaljs or pytest-benchmark[histogram]')

It seems to be an issue in pygal. I also tried: from pygal.graph.box import is_list_like, and it raises a error. 

What is the proper way to workaround it?

**Comment by ionelmc** [comment]
You could downgrade to `pygal<2.1` meanwhile I sort out this regression.

**Comment by yitang** [comment]
have same problem here.

**Comment by ionelmc** [comment]
Fixed in `3.1.0a2`.
