### ISSUE TITLE
Ops/Sec

### ISSUE THREAD

**Issue by thedrow** [ionelmc/pytest-benchmark#55]
Is it possible to display how many benchmarks were run per second?

**Comment by ionelmc** [comment]
There could be a column for this (something computed from avg). Shouldn't be
that hard to add - willing to give it a try? If not I'll add in couple days
(traveling a bit now).

On Wednesday, 29 June 2016, Omer Katz <notifications@github.com> wrote:

> Is it possible to display how many benchmarks were run per second?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ionelmc/pytest-benchmark/issues/55>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAH53SyWuFg-ZyGRtVbGn8V6WAitopg4ks5qQgeDgaJpZM4JAyu0>
> .
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by thedrow** [comment]
I'll get to it if you won't. Probably not soon though.

**Comment by thedrow** [comment]
Added in #78 :)
Thanks @popravich!
