### ISSUE TITLE
Allow elasticsearch authentication besides encoding credentials into url

### ISSUE THREAD

**Issue by varac** [ionelmc/pytest-benchmark#72]
Currrently the only way of using credentials to authenticate against an elasticsearch instance is to encode the username+password in the url.
This is bad when run in CI, i.e. [gitlab unfortunatly still doesn't support protection against leaking secret variables](https://gitlab.com/gitlab-org/gitlab-ce/issues/13784). URls including credentials leak quite easy.
A better way would be to use a config file or a `.netrc` file for credentials.

**Comment by ionelmc** [comment]
As a workaround you could set `addopts=--benchmark-stotage=secretstuff` in pytest.ini programmatically.

**Comment by varac** [comment]
@ionelmc This doesn't solve the problem because on success, pytest-benchmark will still reveal the url including the credentials:

```
...
Saved benchmark data to ['https://admin:PASSWORD@elasticsearch.example.org:9200'] to index benchmark as doctype benchmark
```

**Comment by ionelmc** [comment]
Ok then there are two problems here:

* loading creds from .netrc
* blanking the output (eg: `Saved benchmark data to 'https://***:***@elasticsearch.example.org:9200' to index benchmark as doctype benchmark`)

**Comment by varac** [comment]
I think latter would be the easiest to do, I'd also be fine with using `.netrc` as well.

**Comment by varac** [comment]
Well on a second thought I'd prefer the .netrc option because it seems cleaner and you don't need to think twice in the future of preventing cred leakage when refactoring/adding features.
