### ISSUE TITLE
New filtering of benchmark tests filters out more than it should

### ISSUE THREAD

**Issue by drebs** [ionelmc/pytest-benchmark#86]
I have proposed a modification to filter non-benchmark tests using the `pytest_collect_modifyitems()` hook instead of  `pytest_runtest_call()` (#84). That modification introduced:

- **a bug:** the filtering is finishing too early because of identation problem in the last lines of the filtering function.
- **a conceptual issue:** previous to the modification, the fixtures were instantiated and  the class of the `benchmark` fixture was checked to ensure that the parameter was indeed a benchmark fixture and not just something else called "benchmark". Now the filtering happens before fixtures are instantiated, so we don't have a way to check against their classes. Instead, i proposed to check if there was an argument called `benchmark`, and select the test if so.

I will provide a fix for the bug, and would like to discuss a modification to the conceptual issue.

I have a use case where I create a bunch of other fixtures that use the `benchmark` fixture and modify its behaviour. In this case, if my test functions receive something like `modified_benchmark` they will not be selected if the check is against the exact string of the parameter name.

One simple possibility is to check if there's a test argument name containing `benchmark` as a substring. This would select all tests that have some parameter matching `.*benchmark.*`. Does that make sense? Is there a better way to do it?

**Comment by ionelmc** [comment]
Ideally we'd look into the dependency tree of all the fixtures and select if there's a dependency on `benchmark`. I suspect some horror awaits ...

@RonnyPfannschmidt is it correct that there's no way to know if a test would be using a fixture of certain origin (like a specific plugin) before fixture is actually instantiated?

Now in retrospect, maybe a better way to handle your usecase is to revert #85 and just use `-k 'not benchmark'` when you want to skip early?

**Comment by ionelmc** [comment]
@drebs opinion on `-k` workaround?

**Comment by drebs** [comment]
@ionelmc, that would need me to modify test names to have "benchmark" iff the test is a benchmark, right? I can live with this, if from pytest-benchmark perspective the sanest thing to do is to revert the change.

This is somehow similar to the idea of selecting tests based on the existence of "benchmark" as a substring of the name of any of the arguments. The difference is that the first idea would be a workaround only for me while this second one would be a new "pytest-benchmark" policy for selecting tests (i.e. the effect of "--benchmark").

Conceptually, it seems to me that the best would be to have a way to select/deselect based on the test function arguments, but it seems we are stuck in a situation where we would either have to decide based on the argument names or else we'd have to instantiate the fixtures when they maybe should not have been and then look at their types. Is this true?

Anyway, I'm fine with whatever you decide, and thanks for your input and for maintaining this tool, it is very useful.

**Comment by ionelmc** [comment]
@drebs Marks can also be used (https://docs.pytest.org/en/latest/mark.html?highlight=marks) if you can't have a name convention. I think reverting is better as there is a way to serve both situations with some annoyances (I want to deselect benchmarks VS I don't want fixtures going unused).

**Comment by drebs** [comment]
I'm fine with it. Feel free to close the issue also after reverting.
