### ISSUE TITLE
Sort histogram x-axes ascending (by Trial)

### ISSUE THREAD

**Issue by makmanalp** [ionelmc/pytest-benchmark#90]
In a given histogram image (e.g. let's say I ran `py.test-benchmark compare --name=short --group-by=name --histogram blah/`), it would be awesome to be able to see what the progress in performance in one benchmark has been like across benchmark runs. If you sort the graph by Trial, then this is easy to see.

I think it just requires a modification here:

https://github.com/ionelmc/pytest-benchmark/blob/9953995c680f861608d64692b0b8604fd9995488/src/pytest_benchmark/histogram.py#L94

To change the loop to `for row in sorted(benchmarks, key=lambda x: x['name'])`. Let me know if you'd like me to attempt a PR, or if you'd like to tackle it yourself, @ionelmc !

**Comment by makmanalp** [comment]
Never mind, `--sort=name` does what I need since the name starts with the trial number. Please feel free to close this!

**Comment by ionelmc** [comment]
Very well.
