### ISSUE TITLE
Table Output Control

### ISSUE THREAD

**Issue by jdhardy** [ionelmc/pytest-benchmark#91]
The table output is a bit too verbose for my liking, but I can't see a way to control which columns are emitted (and looking at tables.py it seems to be hardcoded). A `--benchmark-cols=min,median,ops` argument would be ideal.

**Comment by The-Compiler** [comment]
`--benchmark-columns=Min,Max,Median` already is a thing. I can't find it in [the docs](http://pytest-benchmark.readthedocs.io/en/stable/usage.html) though?

**Comment by ionelmc** [comment]
<-- looks like someone forgot to update it :D

**Comment by jdhardy** [comment]
Guido must have left the keys for the time machine lying around. :)

I'll leave this open to get the docs updated.
